[monitor]
interval = 10
maxparallel = 3
timeout = 7
notifyfirstok = false
timeoutretries=2
expirationtime=30
[database]
name = "db.sqlite3"
[telegram]
apikey = "Your API-Key"
admin = "Your Telegram nickname"
debug = true
[redis]
host="localhost"
port=6379
pwd=""
db=0
